// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"vehicle-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/vehicle/gettrajectory",
				Handler: HandleGetTrajectoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicle/online_count",
				Handler: HandleOnlineCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/summary",
				Handler: HandleVehiclesSummaryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/statelist",
				Handler: HandleVehiclesListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/staticlist",
				Handler: HandleListVehiclesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/vehicles",
				Handler: HandleCreateVehicleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/detail",
				Handler: HandleGetVehicleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/vehicles",
				Handler: HandleUpdateVehicleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/vehicles",
				Handler: HandleDeleteVehicleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicle/ws",
				Handler: HandleWebSocketHandler(serverCtx),
			},
		},
	)
}
