// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"vehicle-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/analytics/order_amount",
				Handler: HandleAnalyticsOrderAmountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/analytics/order_count",
				Handler: HandleAnalyticsOrderCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/analytics/overview",
				Handler: HandleAnalyticsOverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/vehicle/gettrajectory",
				Handler: HandleGetTrajectoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicle/online_count",
				Handler: HandleOnlineCountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/summary",
				Handler: HandleVehiclesSummaryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/list",
				Handler: HandleVehiclesListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicles/",
				Handler: HandleVehicleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/vehicle/ws",
				Handler: HandleWebSocketHandler(serverCtx),
			},
		},
	)
}
