# version: '3.8'

services:
  orders-api:
    build: .
    container_name: orders-api
    ports:
      - "18887:18887"  # 订单服务端口
    volumes:
      - ./log:/app/log
    environment:
      - TZ=Asia/Shanghai
    networks:
      - my-network
    restart: always

networks:
  my-network:
    external: true
    name: my-network
