// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"route-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/route/create",
				Handler: RouteCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/route/delete",
				Handler: RouteDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/route/detail/:routeId",
				Handler: GetRouteInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/route/list",
				Handler: GetRouteListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/route/update",
				Handler: RouteUpdateHandler(serverCtx),
			},
		},
	)
}
