// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"gridmenber-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/gridMember/create",
				Handler: GridMemberCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gridMember/delete",
				Handler: GridMemberDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/gridMember/detail/:gridMemberId",
				Handler: GetGridMemberInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/gridMember/list",
				Handler: GetGridMemberListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/gridMember/update",
				Handler: GridMemberUpdateHandler(serverCtx),
			},
		},
	)
}
