// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"orders-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order/create",
				Handler: OrderCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/delete",
				Handler: OrderDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order/detail/:orderId",
				Handler: GetOrderInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order/list",
				Handler: GetOrderListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order/stats",
				Handler: OrderStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/update",
				Handler: OrderUpdateHandler(serverCtx),
			},
		},
	)
}
