// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type BaseResp struct {
	Code int    `json:"code"` // 0=成功，非0=失败
	Msg  string `json:"msg"`
}

type GridMemberCreateInfo struct {
	GridMemberName  string `json:"gridMemberName"`
	GridMemberPhone string `json:"gridMemberPhone"`
	IsGridId        string `json:"isGridId,optional"`
	Status          string `json:"status,optional"`
	Note            string `json:"note,optional"`
}

type GridMemberDeleteReq struct {
	GridMemberId string `json:"gridMemberId"`
}

type GridMemberInfoResp struct {
	GridMemberId    string `json:"gridMemberId"`    // 网格员编号，格式 GM - 入网日期(yyyymmdd) - 6位随机码(含数字和字母)
	EntryTime       string `json:"entryTime"`       // 网格员入网时间，格式 yyyymmdd
	GridMemberName  string `json:"gridMemberName"`  // 网格员姓名
	GridMemberPhone string `json:"gridMemberPhone"` // 网格员联系方式
	IsGridId        string `json:"isGridId"`        // 所属网格编号
	Status          string `json:"status"`          // 网格员状态
	Note            string `json:"note"`            // 备注
}

type GridMemberListReq struct {
	StartTime string `json:"startTime,optional"` // 筛选时间起点，入网时间，格式"yyyyMMddHHmmss"，例：2024012409500
	EndTime   string `json:"endTime,optional"`   // 筛选时间终点，格式"yyyyMMddHHmmss"，例：2024012409500
	Status    string `json:"status,optional"`    // 筛选，网格员状态，在职/正常、在职/排休、在职/请假、离职/流程中、离职/已离职
	IsGridId  string `json:"isGridId,optional"`
}

type GridMemberListResp struct {
	GridMembersList []GridMemberInfoResp `json:"gridMembersList"`
	Total           int                  `json:"total"`
}

type GridMemberUpdateReq struct {
	GridMemberId    string `json:"gridMemberId"`
	Status          string `json:"status,optional"`
	GridMemberPhone string `json:"gridMemberPhone,optional"`
	IsGridId        string `json:"isGridId,optional"`
	Note            string `json:"note,optional"`
}
